const mitigationData = {
  mitigationEffects: {
    Blackmage: [
      {
        name: "Addle",
        type: "debuff",
        target: "self",
        amount: 5,
        condition: "physical damage",
        source_job: "Blackmage",
        granted_by: null,
      },
      {
        name: "Addle",
        type: "debuff",
        target: "self",
        amount: 10,
        condition: "magical damage",
        source_job: "Blackmage",
        granted_by: null,
      },
    ],
    Summoner: [
      {
        name: "Addle",
        type: "debuff",
        target: "self",
        amount: 5,
        condition: "physical damage",
        source_job: "Summoner",
        granted_by: null,
      },
      {
        name: "Addle",
        type: "debuff",
        target: "self",
        amount: 10,
        condition: "magical damage",
        source_job: "Summoner",
        granted_by: null,
      },
    ],
    Scholar: [
      {
        name: "Fey Illumination",
        type: "reduction",
        target: "party",
        amount: 5,
        condition: "magical damage",
        source_job: "Scholar",
        granted_by: null,
      },
      {
        name: "Fey Illumination",
        type: "reduction",
        target: "party",
        amount: 5,
        condition: "magical damage",
        source_job: "Scholar",
        granted_by: "Fey Illumination",
      },
      {
        name: "Sacred Soil",
        type: "reduction",
        target: "party",
        amount: 10,
        condition: null,
        source_job: "Scholar",
        granted_by: null,
      },
      {
        name: "Desperate Measures",
        type: "reduction",
        target: "party",
        amount: 10,
        condition: null,
        source_job: "Scholar",
        granted_by: "Expedient",
      },
      {
        name: "Seraphic Illumination",
        type: "reduction",
        target: "party",
        amount: 5,
        condition: "magical damage",
        source_job: "Scholar",
        granted_by: null,
      },
    ],
    DarkKnight: [
      {
        name: "Shadow Wall",
        type: "reduction",
        target: "self",
        amount: 30,
        condition: null,
        source_job: "DarkKnight",
        granted_by: null,
      },
      {
        name: "Dark Mind",
        type: "reduction",
        target: "self",
        amount: 10,
        condition: "physical damage",
        source_job: "DarkKnight",
        granted_by: null,
      },
      {
        name: "Dark Mind",
        type: "reduction",
        target: "self",
        amount: 20,
        condition: "magical damage",
        source_job: "DarkKnight",
        granted_by: null,
      },
      {
        name: "Dark Missionary",
        type: "reduction",
        target: "party",
        amount: 5,
        condition: "physical damage",
        source_job: "DarkKnight",
        granted_by: null,
      },
      {
        name: "Dark Missionary",
        type: "reduction",
        target: "party",
        amount: 10,
        condition: "magical damage",
        source_job: "DarkKnight",
        granted_by: null,
      },
      {
        name: "Oblation",
        type: "reduction",
        target: "ally",
        amount: 10,
        condition: null,
        source_job: "DarkKnight",
        granted_by: null,
      },
      {
        name: "Shadowed Vigil",
        type: "reduction",
        target: "self",
        amount: 40,
        condition: null,
        source_job: "DarkKnight",
        granted_by: null,
      },
      {
        name: "Rampart",
        type: "reduction",
        target: "self",
        amount: 20,
        condition: null,
        source_job: "DarkKnight",
        granted_by: null,
      },
      {
        name: "Reprisal",
        type: "debuff",
        target: "enemy",
        amount: 10,
        condition: null,
        source_job: "DarkKnight",
        granted_by: null,
      },
    ],
    Gunbreaker: [
      {
        name: "Camouflage",
        type: "reduction",
        target: "self",
        amount: 10,
        condition: null,
        source_job: "Gunbreaker",
        granted_by: null,
      },
      {
        name: "Nebula",
        type: "reduction",
        target: "self",
        amount: 30,
        condition: null,
        source_job: "Gunbreaker",
        granted_by: null,
      },
      {
        name: "Heart of Light",
        type: "reduction",
        target: "party",
        amount: 5,
        condition: "physical damage",
        source_job: "Gunbreaker",
        granted_by: null,
      },
      {
        name: "Heart of Light",
        type: "reduction",
        target: "party",
        amount: 10,
        condition: "magical damage",
        source_job: "Gunbreaker",
        granted_by: null,
      },
      {
        name: "Heart of Stone",
        type: "reduction",
        target: "ally",
        amount: 15,
        condition: null,
        source_job: "Gunbreaker",
        granted_by: null,
      },
      {
        name: "Heart of Corundum",
        type: "reduction",
        target: "ally",
        amount: 15,
        condition: null,
        source_job: "Gunbreaker",
        granted_by: null,
      },
      {
        name: "Clarity of Corundum",
        type: "reduction",
        target: "ally",
        amount: 15,
        condition: null,
        source_job: "Gunbreaker",
        granted_by: "Heart of Corundum",
      },
      {
        name: "Great Nebula",
        type: "reduction",
        target: "self",
        amount: 40,
        condition: null,
        source_job: "Gunbreaker",
        granted_by: null,
      },
      {
        name: "Rampart",
        type: "reduction",
        target: "self",
        amount: 20,
        condition: null,
        source_job: "Gunbreaker",
        granted_by: null,
      },
      {
        name: "Reprisal",
        type: "debuff",
        target: "enemy",
        amount: 10,
        condition: null,
        source_job: "Gunbreaker",
        granted_by: null,
      },
    ],
    Bard: [
      {
        name: "Troubadour",
        type: "reduction",
        target: "party",
        amount: 15,
        condition: null,
        source_job: "Bard",
        granted_by: null,
      },
    ],
    Samurai: [
      {
        name: "Third Eye",
        type: "reduction",
        target: "self",
        amount: 10,
        condition: null,
        source_job: "Samurai",
        granted_by: null,
      },
      {
        name: "Tengentsu",
        type: "reduction",
        target: "self",
        amount: 10,
        condition: null,
        source_job: "Samurai",
        granted_by: null,
      },
      {
        name: "Tengentsu's Foresight",
        type: "reduction",
        target: "self",
        amount: 10,
        condition: null,
        source_job: "Samurai",
        granted_by: "Tengentsu",
      },
      {
        name: "Feint",
        type: "debuff",
        target: "self",
        amount: 10,
        condition: "physical damage",
        source_job: "Samurai",
        granted_by: null,
      },
      {
        name: "Feint",
        type: "debuff",
        target: "self",
        amount: 5,
        condition: "magical damage",
        source_job: "Samurai",
        granted_by: null,
      },
    ],
    Viper: [
      {
        name: "Feint",
        type: "debuff",
        target: "self",
        amount: 10,
        condition: "physical damage",
        source_job: "Viper",
        granted_by: null,
      },
      {
        name: "Feint",
        type: "debuff",
        target: "self",
        amount: 5,
        condition: "magical damage",
        source_job: "Viper",
        granted_by: null,
      },
    ],
    Paladin: [
      {
        name: "Sheltron",
        type: "reduction",
        target: "self",
        amount: 15,
        condition: null,
        source_job: "Paladin",
        granted_by: null,
      },
      {
        name: "Sentinel",
        type: "reduction",
        target: "self",
        amount: 30,
        condition: null,
        source_job: "Paladin",
        granted_by: null,
      },
      {
        name: "Intervention",
        type: "reduction",
        target: "ally",
        amount: 10,
        condition: null,
        source_job: "Paladin",
        granted_by: null,
      },
      {
        name: "Intervention",
        type: "reduction",
        target: "ally",
        amount: 10,
        condition: "if Rampart or Guardian are active",
        source_job: "Paladin",
        granted_by: null,
      },
      {
        name: "Knight's Resolve",
        type: "reduction",
        target: "ally",
        amount: 10,
        condition: null,
        source_job: "Paladin",
        granted_by: "Intervention",
      },
      {
        name: "Passage of Arms",
        type: "reduction",
        target: "party",
        amount: 15,
        condition: null,
        source_job: "Paladin",
        granted_by: null,
      },
      {
        name: "Holy Sheltron",
        type: "reduction",
        target: "self",
        amount: 15,
        condition: null,
        source_job: "Paladin",
        granted_by: null,
      },
      {
        name: "Knight's Resolve",
        type: "reduction",
        target: "self",
        amount: 15,
        condition: null,
        source_job: "Paladin",
        granted_by: "Holy Sheltron",
      },
      {
        name: "Guardian",
        type: "reduction",
        target: "self",
        amount: 40,
        condition: null,
        source_job: "Paladin",
        granted_by: null,
      },
      {
        name: "Rampart",
        type: "reduction",
        target: "self",
        amount: 20,
        condition: null,
        source_job: "Paladin",
        granted_by: null,
      },
      {
        name: "Reprisal",
        type: "debuff",
        target: "enemy",
        amount: 10,
        condition: null,
        source_job: "Paladin",
        granted_by: null,
      },
    ],
    Machinist: [
      {
        name: "Tactician",
        type: "reduction",
        target: "party",
        amount: 15,
        condition: null,
        source_job: "Machinist",
        granted_by: null,
      },
      {
        name: "Dismantle",
        type: "debuff",
        target: "self",
        amount: 10,
        condition: null,
        source_job: "Machinist",
        granted_by: null,
      },
    ],
    Whitemage: [
      {
        name: "Temperance",
        type: "reduction",
        target: "party",
        amount: 10,
        condition: null,
        source_job: "Whitemage",
        granted_by: null,
      },
      {
        name: "Aquaveil",
        type: "reduction",
        target: "ally",
        amount: 15,
        condition: null,
        source_job: "Whitemage",
        granted_by: null,
      },
    ],
    Astrologian: [
      {
        name: "Collective Unconscious",
        type: "reduction",
        target: "party",
        amount: 10,
        condition: null,
        source_job: "Astrologian",
        granted_by: null,
      },
      {
        name: "Exaltation",
        type: "reduction",
        target: "ally",
        amount: 10,
        condition: null,
        source_job: "Astrologian",
        granted_by: null,
      },
      {
        name: "Sun Sign",
        type: "reduction",
        target: "party",
        amount: 10,
        condition: null,
        source_job: "Astrologian",
        granted_by: null,
      },
      {
        name: "The Bole",
        type: "reduction",
        target: "ally",
        amount: 10,
        condition: null,
        source_job: "Astrologian",
        granted_by: null,
      },
    ],
    Warrior: [
      {
        name: "Vengeance",
        type: "reduction",
        target: "self",
        amount: 30,
        condition: "physical damage",
        source_job: "Warrior",
        granted_by: null,
      },
      {
        name: "Raw Intuition",
        type: "reduction",
        target: "self",
        amount: 10,
        condition: null,
        source_job: "Warrior",
        granted_by: null,
      },
      {
        name: "Nascent Glint",
        type: "reduction",
        target: "ally",
        amount: 10,
        condition: null,
        source_job: "Warrior",
        granted_by: "Nascent Flash",
      },
      {
        name: "Stem the Flow",
        type: "reduction",
        target: "ally",
        amount: 10,
        condition: null,
        source_job: "Warrior",
        granted_by: "Nascent Flash",
      },
      {
        name: "Bloodwhetting",
        type: "reduction",
        target: "self",
        amount: 10,
        condition: null,
        source_job: "Warrior",
        granted_by: null,
      },
      {
        name: "Stem the Flow",
        type: "reduction",
        target: "self",
        amount: 10,
        condition: null,
        source_job: "Warrior",
        granted_by: "Bloodwhetting",
      },
      {
        name: "Damnation",
        type: "reduction",
        target: "self",
        amount: 40,
        condition: "physical damage",
        source_job: "Warrior",
        granted_by: null,
      },
      {
        name: "Rampart",
        type: "reduction",
        target: "self",
        amount: 20,
        condition: null,
        source_job: "Warrior",
        granted_by: null,
      },
      {
        name: "Reprisal",
        type: "debuff",
        target: "enemy",
        amount: 10,
        condition: null,
        source_job: "Warrior",
        granted_by: null,
      },
    ],
    Pictomancer: [
      {
        name: "Addle",
        type: "debuff",
        target: "self",
        amount: 5,
        condition: "physical damage",
        source_job: "Pictomancer",
        granted_by: null,
      },
      {
        name: "Addle",
        type: "debuff",
        target: "self",
        amount: 10,
        condition: "magical damage",
        source_job: "Pictomancer",
        granted_by: null,
      },
    ],
    Monk: [
      {
        name: "Riddle of Earth",
        type: "reduction",
        target: "self",
        amount: 20,
        condition: null,
        source_job: "Monk",
        granted_by: null,
      },
      {
        name: "Feint",
        type: "debuff",
        target: "self",
        amount: 10,
        condition: "physical damage",
        source_job: "Monk",
        granted_by: null,
      },
      {
        name: "Feint",
        type: "debuff",
        target: "self",
        amount: 5,
        condition: "magical damage",
        source_job: "Monk",
        granted_by: null,
      },
    ],
    Dancer: [
      {
        name: "Shield Samba",
        type: "reduction",
        target: "party",
        amount: 15,
        condition: null,
        source_job: "Dancer",
        granted_by: null,
      },
    ],
    Reaper: [
      {
        name: "Feint",
        type: "debuff",
        target: "self",
        amount: 10,
        condition: "physical damage",
        source_job: "Reaper",
        granted_by: null,
      },
      {
        name: "Feint",
        type: "debuff",
        target: "self",
        amount: 5,
        condition: "magical damage",
        source_job: "Reaper",
        granted_by: null,
      },
    ],
    RedMage: [
      {
        name: "Magick Barrier",
        type: "reduction",
        target: "party",
        amount: 10,
        condition: "magical damage",
        source_job: "RedMage",
        granted_by: null,
      },
      {
        name: "Addle",
        type: "debuff",
        target: "self",
        amount: 5,
        condition: "physical damage",
        source_job: "RedMage",
        granted_by: null,
      },
      {
        name: "Addle",
        type: "debuff",
        target: "self",
        amount: 10,
        condition: "magical damage",
        source_job: "RedMage",
        granted_by: null,
      },
    ],
    Dragoon: [
      {
        name: "Feint",
        type: "debuff",
        target: "self",
        amount: 10,
        condition: "physical damage",
        source_job: "Dragoon",
        granted_by: null,
      },
      {
        name: "Feint",
        type: "debuff",
        target: "self",
        amount: 5,
        condition: "magical damage",
        source_job: "Dragoon",
        granted_by: null,
      },
    ],
    Ninja: [
      {
        name: "Feint",
        type: "debuff",
        target: "self",
        amount: 10,
        condition: "physical damage",
        source_job: "Ninja",
        granted_by: null,
      },
      {
        name: "Feint",
        type: "debuff",
        target: "self",
        amount: 5,
        condition: "magical damage",
        source_job: "Ninja",
        granted_by: null,
      },
    ],
    Sage: [
      {
        name: "Kerachole",
        type: "reduction",
        target: "party",
        amount: 10,
        condition: null,
        source_job: "Sage",
        granted_by: null,
      },
      {
        name: "Taurochole",
        type: "reduction",
        target: "ally",
        amount: 10,
        condition: null,
        source_job: "Sage",
        granted_by: null,
      },
      {
        name: "Holos",
        type: "reduction",
        target: "party",
        amount: 10,
        condition: null,
        source_job: "Sage",
        granted_by: null,
      },
    ],
  },
  aliases: {
    // "alias": "canonical name"
    Paladin: {
      "Arms Up": "Passage of Arms",
    },
  },
};

export default mitigationData;
